server:
  port: 8082
spring:
  application:
    name: MultiTenant-Schedular
  datasource:
    url: 'jdbc:postgresql://localhost:5432/MultiTenant'
    username: 'postgres'
    password: 'saibaba5854'
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
  main:
    allow-circular-references: true